### ISSUE TITLE
部分向量化执行函数的优先实现

### ISSUE THREAD

**Issue by HappenLee** [doris-vectorized/doris-vectorized#129]
##### 聚合函数

- [] ndv

##### 计算判断函数

- [] hex
- [] to_base64
- [] aes_encrypt
- [] / % 除法与取余计算，我们需要支持返回null，在除0的时候。这部分需要修改函数的执行框架。
- [] like
- [] md5
- [] md5sum
- [] rand
- [] bin

##### null 相关

- [] nullif
- [] ifnull
- [] eq_for_null

##### 时间相关

- [] makedate

##### 字符串相关

- [] split_part

##### 其他

- [] parse_url

##### bitmap相关

- [] bitmap_to_string
- [] bitmap_min
- [x] bitmap_max

**Comment by zbtzbtzbt** [comment]
hex unhex is finished

**Comment by wangbo** [comment]
- [ ] like

**Comment by zenoyang** [comment]
- [x] to_base64 is done

**Comment by wangshuo128** [comment]
woking on aes_encrypt

**Comment by xinghuayu007** [comment]
work on ifnull

**Comment by zenoyang** [comment]
working on `md5` and `md5sum `

**Comment by azurenake** [comment]
work on nullif

**Comment by Gabriel39** [comment]
working on `bin`

**Comment by weizuo93** [comment]
working on ` aes_encrypt`

**Comment by xinghuayu007** [comment]
work on rand

**Comment by Gabriel39** [comment]
work on `split_part`

**Comment by zbtzbtzbt** [comment]
simplify `bin` code

**Comment by zbtzbtzbt** [comment]
refactor `round`
