### ISSUE TITLE
[Bug] Bug函数Case

### ISSUE THREAD

**Issue by HappenLee** [doris-vectorized/doris-vectorized#139]
### Table
```
CREATE TABLE `test` (
  `k1` tinyint(4) NULL COMMENT "",
  `k2` smallint(6) NULL COMMENT "",
  `k3` int(11) NULL COMMENT "",
  `k4` bigint(20) NULL COMMENT "",
  `k5` decimal(9, 3) NULL COMMENT "",
  `k6` char(5) NULL COMMENT "",
  `k10` date NULL COMMENT "",
  `k11` datetime NULL COMMENT "",
  `k7` varchar(20) NULL COMMENT "",
  `k8` double MAX NULL COMMENT "",
  `k9` float SUM NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`, `k6`, `k10`, `k11`, `k7`)
COMMENT "OLAP"
PARTITION BY RANGE(`k1`)
(PARTITION p1 VALUES [("-128"), ("-64")),
PARTITION p2 VALUES [("-64"), ("0")),
PARTITION p3 VALUES [("0"), ("64")),
PARTITION p4 VALUES [("64"), (MAXVALUE)))
DISTRIBUTED BY HASH(`k1`) BUCKETS 5
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2"
); 
```

### CASE
- [ ] select concat(k10, k6) from test order by k1, k2, k3, k4
- [ ] select upper(k1), upper(k2), upper(k3), upper(k4), upper(k6), upper(k7), \t\t    upper(k10), upper(k11) from test \t\t    order by k1, k2, k3, k4
- [ ] select ln(abs(k1)), ln(abs(k2)), ln(abs(k3)), ln(abs(k4)), ln(abs(k5)), ln(abs(k8)), \t\t    ln(abs(k9)) from test where k1<>0 and k2<>0 and k3<>0 and k4<>0 and k5<>0 \t\t    and k8<>0 and k9<>0\t\t    order by k1, k2, k3, k4
- [ ] select k1, -k2, -k3, -k4, -k8, -k9,  -k5 from test order by k1, k2, k3, k4
- [x] select k1, pow(k1, -2), pow(k2, -2), pow(k3, -2), pow(k4, -2), pow(k5, -2),            pow(k8, -2), pow(k9, -2) from test where k1<>0 and k2<>0 and k3<>0 and k4<>0             and k5<>0 and k8<>0 and k9<>0             order by k1, k2, k3, k4
- [ ] select sign(k1), sign(k2), sign(k3), sign(k4), sign(k5), sign(k8), sign(k9) from test where k1<>0 and k2<>0 and k3<>0 and k4<>0 and k5<>0 and k8<>0 and k9<>0 order by k1, k2, k3, k4
- [ ] SELECT RPAD('hi',1,'123')
- [ ] select str_to_date('15 September 2001', '%d %M %Y'), str_to_date('15 SEPTEMB 2001', '%d %M %Y')
- [ ] select DATE_ADD(k10, INTERVAL 13 WEEK) from test \t\t    order by k1, k2, k3, k4
- [ ] select timediff('1019-02-28 00:00:00', '2019-02-28 00:00:00'),         timediff('2015-01-25 00:00:00', '2015-02-28 22:50:00'),         timediff('2015-01-25 00:00:00', '2015-01-25 00:00:00')
- [ ] select TIMESTAMPDIFF(DAY, k10, cast(k11 as date)), TIMESTAMPDIFF(DAY, cast(k10 as datetime), k11),             TIMESTAMPDIFF(DAY, k10, k11) from test order by k1, k2, k3, k4
- [ ] select TIMESTAMPADD(DAY, k1, k10), TIMESTAMPADD(DAY, k2, k11), TIMESTAMPADD(DAY, 100, k10)             from test order by k1,k2,k3,k4
- [ ] select count(k5), k2 from test c, (select ca.k1 okey, cb.k2 opr from baseall ca, test cb where \t\t    ca.k1=cb.k1 and ca.k2+cb.k2>2) v group by k2 order by 1, 2

**Comment by BiteTheDDDDt** [comment]
- [x] SELECT RPAD('hi',1,'123')

**Comment by BiteTheDDDDt** [comment]
- [X] select upper(k1), upper(k2), upper(k3), upper(k4), upper(k6), upper(k7), \t\t upper(k10), upper(k11) from test \t\t order by k1, k2, k3, k4

**Comment by zbtzbtzbt** [comment]
补充一个，不知道是不是我环境问题，经常测试时发生BE挂掉的情况
concat、lpad、rpad都发生过
```
mysql> select concat(str,'wo') from table_test;
ERROR 2013 (HY000): Lost connection to MySQL server during query
mysql> select concat(str,'wo') from table_test;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1
Current database: test_db
```

**Comment by HappenLee** [comment]
@zbtzbtzbt 尝试合入我修复bug的patch之后进行继续验证
